[default]
extend-ignore-identifiers-re = ["NdArray*", "ND"]

[files]
extend-exclude = [
    "*.onnx",
    "*.proto",
    # ImageNet labels contain scientific names that look like typos
    "examples/image-classification-web/src/model/label.txt",
]

[default.extend-words]
# Don't correct "arange" which is intentional
arange = "arange"
